### ISSUE TITLE
Steps no longer seem to work

### ISSUE THREAD

**Issue by jefffhaynes** [edgeimpulse/example-custom-ml-block-keras#2]
There seem to be a few issue with the steps as outlined in the readme.

Firstly, there is no longer a choice for "other" as far as I can tell.  

Also, running ```edge-impulse-blocks runner --download-data data/``` results in:

```
Edge Impulse Blocks v1.17.0
[BLK] Selecting project with ID 64474
Error while running block: Error: No learning block found with ID 187
    at Request._callback (/usr/local/lib/node_modules/edge-impulse-cli/build/sdk/studio/sdk/api/learnApi.js:692:36)
    at Request.self.callback (/usr/local/lib/node_modules/edge-impulse-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/edge-impulse-cli/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/edge-impulse-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

The run step is also failing for me, but I don't know if that's because of the prior steps failing or something else.

**Comment by janjongboom** [comment]
Verified everything today (and updated to TF2.19).
